# scrape_config.tpl.yml
scrape_configs:
  - job_name: "secure_exporter"
    static_configs:
      - targets: ["10.0.0.123:8080"]
    basic_auth:
      username: "${SCRAPE_USERNAME}"
      password: "${SCRAPE_PASSWORD}"
